global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'AlertManager <support@example.com>'
  smtp_require_tls: true
  smtp_hello: 'alertmanager'
  smtp_auth_username: 'support@example.com'
  smtp_auth_password: '########'

#  slack_api_url: 'https://hooks.slack.com/services/x/xx/xxx'

route:
  group_by: ['instance', 'alert']
  group_wait: 30s
  group_interval: 5m
  #repeat_interval: 3h
  receiver: email-me

receivers:
  - name: 'email-me'
    email_configs:
      - to: 'user@example.com'
        #    slack_configs:
      # https://prometheus.io/docs/alerting/configuration/#slack_config
      # - channel: 'system_events'
      #- username: 'AlertManager'
      #- icon_emoji: ':joy:'

~                                                                                                                                                                                                                  
~                                                                                                                                                                                                                  
~                                                                                                                                                                                                                  
~                                 
